version: '3.8'
services:
  postgres-beautique:
    image: postgres
    hostname: postgres-beautique
    environment:
        POSTGRES_DB: beautique
        POSTGRES_USER: beautique
        POSTGRES_PASSWORD: beautique
    volumes:
      - '/c/Users/h/Desktop/java/cqrs/db-beautique:/var/lib/postgresql/data'
      - './init-beautique-schema.sql:/docker-entrypoint-initdb.d/init-beautique-schema.sql'
    ports:
      - '3334:5432'
    networks:
      - beautique-network
  rabbitmq:
      image: 'rabbitmq:3-management'
      hostname: rabbitmq
      environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
      ports:
        - '5672:5672'
        - '15672:15672'
      networks:
        - beautique-network
      volumes:
      - '/c/Users/h/Desktop/java/cqrs/rabbitmq-data:/var/lib/rabbitmq'
      - '/c/Users/h/Desktop/java/cqrs/rabbitmq-log:/var/log/rabbitmq'
networks:
    beautique-network:
      driver: bridge
